### ISSUE TITLE
Odd results with few values?

### ISSUE THREAD

**Issue by cristianocca** [axiak/fuzzyset#10]
```
f = FuzzySet()
f.add(u'Conor Hedley')
print f.get(u'directory manager')
>>> [[(0.23529411764705888, u'Conor Hedley')]
f.add(u'man')
print f.get(u'directory manager')
>>> [(0.17647058823529416, u'man')]
```
How exactly does the first result have a 0.23 match? And how does the match actually gets lower with a value that seems actually closer?
I don't really mind the inconsistency, but the javascript version of this library behaves as expected (no odd match with "Conor Hedley") for example.

**Comment by axiak** [comment]
Hey -- sorry for the late comment. By default we're using edit distance by the well-known Levenshtein algorithm to determine similarity. As you've noted there are times when it seems odd. You can specify `use_levenshtein=False` to get cosine similarity based on matching trigrams/bigrams. Here's an example of that:

```python
>>> f = FuzzySet(use_levenshtein=False)
>>> f.add(u'Conor Hedley')
>>> print(f.get(u'directory manager'))
[(0.06537204504606135, 'Conor Hedley')]
>>> f.add(u'man')
>>> print(f.get(u'directory manager'))
[(0.140028008402801, 'man')]

```
