### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by tonycalebs** [axiak/fuzzyset#15]
Please help am having this error
Traceback (most recent call last):
  File "C:\Users\tonyc\Documents\tuberculosis\Tuberculosis_Diagnosis_Expert_System_Using_Fuzzy_Logic-master\Diabetes_Diagnosis_Expert_System_Using_Fuzzy_Logic-master\code\template.py", line 176, in <module>
    rules, values = generateRules()
  File "C:\Users\tonyc\Documents\tuberculosis\Tuberculosis_Diagnosis_Expert_System_Using_Fuzzy_Logic-master\Diabetes_Diagnosis_Expert_System_Using_Fuzzy_Logic-master\code\template.py", line 156, in generateRules
    cough = fuzzySets(cough_low, cough_med, cough_high, str(row[1]))
  File "C:\Users\tonyc\Documents\tuberculosis\Tuberculosis_Diagnosis_Expert_System_Using_Fuzzy_Logic-master\Diabetes_Diagnosis_Expert_System_Using_Fuzzy_Logic-master\code\template.py", line 46, in fuzzySets
    if(val < str(med[0])):
TypeError: 'int' object is not subscriptable

**Comment by tonycalebs** [comment]
Thanks Axiak, here is the code

import csv

#Defining Constants
#Coughing
cough_low = 0
cough_med = 1
cough_high = 2

#Chest Pain
chest_low = 0
chest_high = 1

#Haemoptysis
haemoptysis_low = 0
haemoptysis_high = 1
#Fever
fever_low = 0
fever_med = 1
fever_high = 2
#Loss of appetite
appetite_low = 0
appetite_high = 1
#Smoking Adiction
smoking_low = 0
smoking_med = 1
smoking_High = 2
#ECG Vaccine
ecg_low = 0
ecg_high = 1
#Wieght Loss
weight_low = 0
weight_high = 1
#Malaise
malaise_low = 0
malaise_high = 1
#Tuberculosis function
tb_low = 0
tb_med = 1
tb_high = (2,3)



values_list = []

def fuzzySets(low, med, high, val):
    if(val < (med[0])):
        return 'L'
    elif(val >= (med[0]) and val <low):
        a = ((med[0])+low)/2
        if(val >= a):
            return 'M'
        else:
            return 'L'
    elif (val >= low and val < high):
        return 'M'
    elif (val >= high and val < med[1]):
        a = ((med[1]) + high) / 2
        if (val >= a):
            return 'H'
        else:
            return 'M'
    elif (val >= med[1]):
        return 'H'


def calculate_degree_of_attr(attr, value, low, med, high):
    deg = 0
    if(attr == 'L'):
        if(value >= med[0]):
            dist = abs(med[0] - value)
            deg = 1 - (dist * abs(med[0] - low)) / 100
        else:
            deg = 1
    elif(attr == 'M'):
        dist = ((med[0]+med[1]) / 2) - value
        deg = 1 - abs(dist) / 100
    elif(attr == 'H'):
        if (value <= med[1]):
            dist = abs(med[1] - value)
            deg = 1 - (dist * abs(med[1] - high)) / 100
        else:
            deg = 1

    return deg

def calculate_degree_of_rule(rule):
    global values_list
    values = values_list[rule[0]]
    deg_cough = calculate_degree_of_attr(rule[1], values[1], cough_low, cough_med, cough_high)
    deg_chest = calculate_degree_of_attr(rule[2], values[2], chest_low, chest_high)
    deg_haemoptysis = calculate_degree_of_attr(rule[3], values[3],  haemoptysis_high)
    deg_fever = calculate_degree_of_attr(rule[4], values[4], fever_low, fever_med, fever_high)
    deg_appetite = calculate_degree_of_attr(rule[5], values[5], appetite_low, appetite_high)
    deg_smoking = calculate_degree_of_attr(rule[6], values[5], appetite_low, appetite_med, smoking_high)
    deg_ecg = calculate_degree_of_attr(rule[7], values[7], ecg_low, ecg_high)
    deg_weight = calculate_degree_of_attr(rule[8], values[8], weight_low, weight_high)
    deg_malaise = calculate_degree_of_attr(rule[9], values[9], malaise_low, malaise_high)

    deg = deg_cough * deg_chest * deg_haemoptysis * deg_fever * deg_appetite *deg_smoking *deg_ecg *deg_weight *deg_malaise

    return deg

def conflict_rssolve(rule1, rule2):
    if(rule1[10] == rule2[10]):
        return rule1[10]
    else:
        #resolve conflict
        deg_rule1 = calculate_degree_of_rule(rule1)
        deg_rule2 = calculate_degree_of_rule(rule2)

        if(deg_rule1 >= deg_rule2):
            return rule1[10]
        else:
            return rule2[10]


def check_conflict(rules_list):
    qualified_rules_list = []
    count = 0
    flag = 1
    for rule in rules_list:
        if(count <= len(rules_list)):
            print("Rule from rule list  :  ", rule)
            for qrule in qualified_rules_list:
                flag = 1
                print("Rule from qualified rule list  :  ", qrule)
                if(rule[1:10] == qrule[1:10]):
                    print("MATCH IDENTIFIED for ",rule[0], qrule[0])
                    qrule[10] = conflict_rssolve(rule, qrule)
                    flag = 0
                    break
            if flag == 1 :
                print(rule[0], " appended in list")
                qualified_rules_list.append(rule)

        count += 1
    with open("tb_rules.txt", "w") as f_r:
        for r in qualified_rules_list:
            f_r.write("Rule No. "+str(r[0])+" --> "+" If cough is "+str(r[1])+" AND chest is "+str(r[2])+
                      " AND Blood Pressure is "+str(r[3])+" AND fever is "+str(r[4])
                      + " AND appetite is " + str(r[5])+" AND smoking is " + str(r[6])+
                      " AND ecg is " + str(r[7])+" AND weight is " + str(r[8])+
                      " AND malaise is " + str(r[9])+
                      " AND Tuberculosis Status is " + str(r[10])+"\n")
    return qualified_rules_list

def generateRules():
    f = open("tuberculosis.csv", "r")
    reader = csv.reader(f)
    rules_list = []
    global values_list
    for row in reader:
        if(len(row) != 0):
            values = [float(row[0]), float(row[1]), float(row[2]), float(row[3]), float(row[4]), str(row[5]),
                      float(row[6]), float(row[7]), float(row[8]), float(row[9]), float(row[10])]
            cough = fuzzySets(cough_low, cough_med, cough_high, float(row[1]))
            chest = fuzzySets(chest_low, chest_high, float(row[2]))
            haemoptysis = fuzzySets(haemoptysis_low, haemoptysis_high, float(row[3]))
            fever = fuzzySets(fever_low, fever_med, fever_high, float(row[4]))
            appetite = fuzzySets(appetite_low, appetite_high, float(row[5]))
            smoking = fuzzySets(smoking_low, smoking_med, smoking_high, float(row[6]))
            ecg = fuzzySets(ecg_low, ecg_high, float(row[7]))
            weight = fuzzySets(weight_low, weight_high, float(row[8]))
            malaise = fuzzySets(malaise_low, malaise_high, float(row[9]))
            conclusion = float(row[10])
            rule = [float(row[0]), cough, chest, haemoptysis, fever, appetite, tb, diab]
            rules_list.append(rule)
            values_list.append(values)
            row += 1
            

    return rules_list, values_list


if __name__ == '__main__':
    rules, values = generateRules()

    qualified_rules = check_conflict(rules)
    with open("test_rules.csv", "w+") as r_f:
        for q in qualified_rules:
            r = values[q[0]]
            r_f.write(str(r[1])+","+str(r[2])+","+str(r[3])+","+str(r[4])+","+str(r[5])+","+str(r[6])+","+str(r[7])+str(r[8])+str(r[9])+str(r[10])+"\n")
            print(r[0])

**Comment by axiak** [comment]
This code is using its own fuzzy set implementation, not the one in this repository.

**Comment by tonycalebs** [comment]
Please help
