### ISSUE TITLE
How to get index of match in original list?

### ISSUE THREAD

**Issue by nodice73** [axiak/fuzzyset#22]
Hello,

Is it possible to get the index of each result returned by 'get' in the original list passed or added to FuzzySet? For example, I am looking for matches in a list of DNA sequences that have genes associated with them. It would be great if I could use the index from the match to directly look up the gene.

Thank you!

**Comment by axiak** [comment]
fuzzyset doesn't have a notion of order (indeed, it's supposed to feel like a set), so this would be impossible on its own. I would recommend creating a secondary index such as:

```python
seq_idx = {seq: i for i, seq in enumerate(sequences)}
```

**Comment by nodice73** [comment]
Gotcha. I have the secondary index, but I was hoping to avoid the somewhat expensive calls to numpy's 'where' to get it. Thanks anyway.

**Comment by axiak** [comment]
couldn't you search the array and use https://docs.scipy.org/doc/numpy/reference/generated/numpy.searchsorted.html ?

**Comment by nodice73** [comment]
Thanks for the hint. I realized I could do the lookups more efficiently since I have them in a pandas dataframe.
