### ISSUE TITLE
Problem with install to Python3.9

### ISSUE THREAD

**Issue by yuhymuk** [axiak/fuzzyset#28]
pip install fuzzyset
trace 
ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-byd1csue/fuzzyset_7135df109e3b4107a8adf8352d3dea6e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-byd1csue/fuzzyset_7135df109e3b4107a8adf8352d3dea6e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1t1vw2c7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/fuzzyset
         cwd: /tmp/pip-install-byd1csue/fuzzyset_7135df109e3b4107a8adf8352d3dea6e/
    Complete output (137 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/fuzzyset
    copying fuzzyset/__init__.py -> build/lib.linux-x86_64-3.9/fuzzyset
    running build_ext
    building 'cfuzzyset' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/fuzzyset
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.9 -c fuzzyset/cfuzzyset.c -o build/temp.linux-x86_64-3.9/fuzzyset/cfuzzyset.o
    fuzzyset/cfuzzyset.c: In function '__Pyx_modinit_type_init_code':
    fuzzyset/cfuzzyset.c:6309:35: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member named 'tp_print'; did you mean 'tp_dict'?
       __pyx_type_9cfuzzyset_cFuzzySet.tp_print = 0;
                                       ^~~~~~~~
                                       tp_dict
    fuzzyset/cfuzzyset.c: In function '__Pyx_ParseOptionalKeywords':
    fuzzyset/cfuzzyset.c:6778:21: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                         (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
                         ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6778:21: warning: 'PyUnicode_AsUnicode' is deprecated [-Wdeprecated-declarations]
                         (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
                         ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
     Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
                                                 ^~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6778:21: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                         (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
                         ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6778:21: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                         (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
                         ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6778:21: warning: 'PyUnicode_AsUnicode' is deprecated [-Wdeprecated-declarations]
                         (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
                         ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
     Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
                                                 ^~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6778:21: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                         (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
                         ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6794:25: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                             (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
                             ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6794:25: warning: 'PyUnicode_AsUnicode' is deprecated [-Wdeprecated-declarations]
                             (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
                             ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
     Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
                                                 ^~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6794:25: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                             (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
                             ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6794:25: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                             (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
                             ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6794:25: warning: 'PyUnicode_AsUnicode' is deprecated [-Wdeprecated-declarations]
                             (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
                             ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
     Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
                                                 ^~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6794:25: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                             (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
                             ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c: In function '__Pyx_PyUnicode_Substring':
    fuzzyset/cfuzzyset.c:8026:9: warning: 'PyUnicode_FromUnicode' is deprecated [-Wdeprecated-declarations]
             return PyUnicode_FromUnicode(NULL, 0);
             ^~~~~~
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:551:42: note: declared here
     Py_DEPRECATED(3.3) PyAPI_FUNC(PyObject*) PyUnicode_FromUnicode(
                                              ^~~~~~~~~~~~~~~~~~~~~
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-byd1csue/fuzzyset_7135df109e3b4107a8adf8352d3dea6e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-byd1csue/fuzzyset_7135df109e3b4107a8adf8352d3dea6e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1t1vw2c7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/fuzzyset Check the logs for full command output.

**Comment by frumsdotxyz** [comment]
This appears to be tied to this change: https://bugs.python.org/issue37250

**Comment by chenrui333** [comment]
```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.9 -c fuzzyset/cfuzzyset.c -o build/temp.linux-x86_64-3.9/fuzzyset/cfuzzyset.o
fuzzyset/cfuzzyset.c: In function '__Pyx_modinit_type_init_code':
fuzzyset/cfuzzyset.c:6309:35: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member named 'tp_print'; did you mean 'tp_dict'?
__pyx_type_9cfuzzyset_cFuzzySet.tp_print = 0;
^~~~~~~~
```

**Comment by alpae** [comment]
seems that if you regenerate fuzzyset/cfuzzyset.c with a newer cython version, it installs with python3.9.2.

**Comment by davidstrouk** [comment]
Hey, any updates regarding this issue?

**Comment by rgreid** [comment]
https://github.com/axiak/fuzzyset/pull/29 fixes this. While we're waiting for the PR, `pip install git+https://github.com/alpae/fuzzyset` will install @alpae's branch
