### ISSUE TITLE
Add python3 support

### ISSUE THREAD

**Issue by g0ddest** [axiak/fuzzyset#6]
It nice to have python 3 support

**Comment by psychemedia** [comment]
I think the package as installed from github now works with py3 - but this hasn't been pushed to make it directly pip installable other than via git+ ?

**Comment by mz52arsi** [comment]
I am getting this error on installation via
pip3 install fuzzyset

print start round brace is missing I suppose

>>> from fuzzyset import FuzzySet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/fuzzyset/__init__.py", line 123
    print "{}: Could not find".format(line.strip())
                             ^
SyntaxError: invalid syntax

**Comment by psychemedia** [comment]
@mz52arsi Install from Github - `pip3 install git+https://github.com/axiak/fuzzyset.git`

**Comment by axiak** [comment]
I cut a release (0.0.11) which should support python3.
